---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    kubernetes.io/metadata.name: openshift-distributed-tracing
    argocd.argoproj.io/managed-by: openshift-gitops
  name: openshift-distributed-tracing

