---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-notes-app
  namespace: openshift-gitops
spec:
  project: quarkus-notes
  source:
    repoURL: https://github.com/mcaimi/k8s-demo-argocd.git
    targetRevision: master
    path: workload/quarkus-notes/deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
