apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: amq-streams
  kind: kafka-broker
  master: argocd-application

resources:
  - project.yaml
  - operator.yaml
  - broker.yaml
  
