---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-consumer-app
  namespace: openshift-gitops
spec:
  project: quarkus-consumer
  source:
    repoURL: https://github.com/mcaimi/kafka-event-consumer-demo.git
    targetRevision: native
    path: openshift/event-consumer
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
