apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-machine-api
commonLabels:
  app: kube-descheduler
  kind: operator
  master: argocd-application

resources:
  - operatorgroup.yaml
  - subscription.yaml
