---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-cluster-hub
  namespace: openshift-gitops
spec:
  project: ocp-acm
  source:
    repoURL: https://github.com/mcaimi/k8s-demo-argocd.git
    targetRevision: master
    path: config/ocp-acm/hub
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
