bases:
  - ../common
namespace: quarkus-notes
namePrefix: database-
nameSuffix: "-1"
commonLabels:
  app: k8s-postgres-app
commonAnnotations:
  deployedBy: "argocd"
  chain: "devops-pipeline"
  environment: "prod"
patchesStrategicMerge:
- storageclass.yaml
- mem-sizing.yaml
images:
- name: postgres
  newName: docker.io/library/postgres
  newTag: latest
secretGenerator:
- name: postgres-init-secret
  literals:
  - postgres_password=P0stgr3s
  - postgres_db_name=pgdev_db
  - postgres_user_name=pgdev
  - postgres_app_user=dev_user
  - postgres_app_db=dev_db
  - postgres_app_user_password=hibernate
configMapGenerator:
- name: postgres-init-config
  files:
    - postgres-init-db.sh
