apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - argocd-namespace.yaml
  - argocd-admins-group.yaml
  - argocd-clusterrole.yaml
  - argocd-instance.yaml
  - argocd-rbac-cm.yaml
