apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: quarkus-notes-servicemesh
  kind: application-configuration
  master: argocd-application

resources:
  - project.yaml
  - deploy.yaml
