apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: tekton
  kind: operator
  master: argocd-application

resources:
  - project.yaml
  - tekton.yaml
