apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: cluster-logging
  kind: operator
  master: argocd-application

resources:
  - project.yaml
  - cluster-logging.yaml
