apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: openshift-servicemesh
  kind: operator
  master: argocd-application

resources:
  - project.yaml
  - ocp-sm-operator.yaml
  - ocp-sm-cp.yaml
