---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemesh-controlplane
  namespace: openshift-gitops
spec:
  project: ocp-servicemesh
  source:
    repoURL: https://github.com/mcaimi/k8s-demo-argocd.git
    targetRevision: master
    path: config/ocp-servicemesh/controlplane
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
