---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-notes-database-backend
  namespace: argocd
spec:
  project: quarkus-notes
  source:
    repoURL: https://github.com/mcaimi/k8s-demo-argocd.git
    targetRevision: HEAD
    path: database/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

