apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
commonLabels:
  app: oc
  kind: end-user-application-deployment
  master: devops-pipeline

resources:
  - project.yaml
  - backend-database.yaml
  - application-frontend.yaml
