apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management
commonLabels:
  app: cluster-manager
  kind: operator
  master: argocd-application

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
