---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.postgres.destinationrule.name }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.postgres.destinationrule.host }}
  trafficPolicy:
    tls:
      mode: {{ .Values.postgres.destinationrule.tls_policy }}