apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-notes
  namespace: istio-system
spec:
  host: {{ .Values.ingress.exposed_route }}
  port:
    targetPort: http2
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
