apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: event-input-topic
  labels:
    strimzi.io/cluster: "kafka-cluster"
spec:
  partitions: 1
  replicas: 1
