---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ocp-logging-operatorgroup
  namespace: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat 
spec: {}
