apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-logging
  namespace: openshift-logging
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: stable
  installPlanApproval: Automatic
  name: cluster-logging
