---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-frontend-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/quarkus-notes/demo-app-frontend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: k8s-demo-app-github-repo-v2
spec:
  type: git
  params:
  - name: url
    value: https://github.com/mcaimi/servicemesh-demo
  - name: revision
    value: federation
