apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
commonLabels:
  app: openshift-gitops
  kind: operator
  master: argocd-application

resources:
  - project.yaml
  - ocp-gitops.yaml
